[package]
name = "nso-log-reader"
version = "0.1.0"
edition = "2021"

[dependencies]
atty = "0.2"
chrono = "0.4"
clap = { version = "3.2", features = ["derive"] }
glob = "0.3"
owo-colors = "3"
subprocess = "0.2"
