name: Build and Publish

# Run on tags matching "v*"
on:
  push:
    tags:
      - 'v*'

jobs:
  # Build Rust project with cargo and publish
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --release

      - name: Publish
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          TAG="$(echo "${{ github.ref }}" | cut -d/ -f3)"
          gh release create ${{ github.ref }} --generate-notes -t "$TAG (Linux x86_64)" target/release/nso-log-reader
